#!/usr/bin/env python3
"""
Prepare runtime asset folders for trained-mip vs box-average mip comparisons.

Given a trained hierarchical runtime folder, this script creates:

1. A box-averaged runtime folder:
   - same decoder/metadata as the trained runtime
   - mip0 copied from the trained runtime
   - mip1..N recursively generated by 2x2 averaging latent-space values

2. Forced-mip runtime folders:
   - one folder per source variant and mip level
   - each folder exposes only latent0.exr/latent1.exr copied from that mip
   - no latent*_mipN.exr files, so Falcor loads it as a single-level latent texture
"""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path

import Imath
import numpy as np
import OpenEXR


LATENT_PREFIXES = ("latent0", "latent1")


def read_exr_rgba(path: Path) -> np.ndarray:
    exr = OpenEXR.InputFile(str(path))
    try:
        header = exr.header()
        dw = header["dataWindow"]
        width = dw.max.x - dw.min.x + 1
        height = dw.max.y - dw.min.y + 1
        channels = header["channels"]
        arrays = []
        for name in ("R", "G", "B", "A"):
            if name not in channels:
                raise ValueError(f"{path} is missing channel {name}")
            pixel_type = channels[name].type
            raw = exr.channel(name, pixel_type)
            if pixel_type == Imath.PixelType(Imath.PixelType.HALF):
                dtype = np.float16
            elif pixel_type == Imath.PixelType(Imath.PixelType.FLOAT):
                dtype = np.float32
            else:
                raise ValueError(f"Unsupported EXR channel type in {path}: {pixel_type}")
            arrays.append(np.frombuffer(raw, dtype=dtype).reshape(height, width).astype(np.float32))
        return np.stack(arrays, axis=-1)
    finally:
        exr.close()


def write_exr_rgba_half(path: Path, rgba: np.ndarray) -> None:
    rgba = np.asarray(rgba, dtype=np.float16)
    height, width, channels = rgba.shape
    if channels != 4:
        raise ValueError(f"Expected RGBA array, got shape {rgba.shape}")

    header = OpenEXR.Header(width, height)
    pt = Imath.PixelType(Imath.PixelType.HALF)
    header["channels"] = {name: Imath.Channel(pt) for name in ("R", "G", "B", "A")}
    out = OpenEXR.OutputFile(str(path), header)
    try:
        out.writePixels(
            {
                "R": rgba[:, :, 0].tobytes(),
                "G": rgba[:, :, 1].tobytes(),
                "B": rgba[:, :, 2].tobytes(),
                "A": rgba[:, :, 3].tobytes(),
            }
        )
    finally:
        out.close()


def average_2x2(rgba: np.ndarray) -> np.ndarray:
    h, w, c = rgba.shape
    if h < 2 or w < 2:
        return rgba.copy()
    h2 = h // 2
    w2 = w // 2
    cropped = rgba[: h2 * 2, : w2 * 2, :]
    return cropped.reshape(h2, 2, w2, 2, c).mean(axis=(1, 3), dtype=np.float32)


def remove_latents(path: Path) -> None:
    for pattern in ("latent0*.exr", "latent1*.exr", "latent0*.npy", "latent1*.npy"):
        for latent_path in path.glob(pattern):
            latent_path.unlink(missing_ok=True)


def copy_non_latent_files(src: Path, dst: Path) -> None:
    dst.mkdir(parents=True, exist_ok=True)
    for item in src.iterdir():
        if item.is_dir():
            continue
        if item.name.startswith("latent0") or item.name.startswith("latent1"):
            continue
        shutil.copy2(item, dst / item.name)


def copy_runtime_tree(src: Path, dst: Path) -> None:
    print(f"[copy] creating {dst}")
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)


def load_metadata(runtime_dir: Path) -> dict:
    metadata_path = runtime_dir / "metadata.json"
    if not metadata_path.exists():
        return {}
    return json.loads(metadata_path.read_text(encoding="utf-8"))


def write_metadata(runtime_dir: Path, metadata: dict, mip_shapes: list[tuple[int, int]]) -> None:
    if not metadata:
        return
    metadata = dict(metadata)
    metadata["mip_count"] = len(mip_shapes)
    metadata["mip_shapes"] = [[int(w), int(h)] for w, h in mip_shapes]
    metadata["width"] = int(mip_shapes[0][0])
    metadata["height"] = int(mip_shapes[0][1])
    metadata["latent_file_pattern"] = "latent{0,1}_mip{mip}.exr" if len(mip_shapes) > 1 else "latent{0,1}.exr"
    (runtime_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")


def detect_mip_count(runtime_dir: Path) -> int:
    count = 0
    while (runtime_dir / f"latent0_mip{count}.exr").exists() and (runtime_dir / f"latent1_mip{count}.exr").exists():
        count += 1
    if count == 0 and (runtime_dir / "latent0.exr").exists() and (runtime_dir / "latent1.exr").exists():
        count = 1
    if count == 0:
        raise FileNotFoundError(f"No latent EXR files found in {runtime_dir}")
    return count


def latent_path(runtime_dir: Path, prefix: str, mip: int) -> Path:
    mip_path = runtime_dir / f"{prefix}_mip{mip}.exr"
    if mip_path.exists():
        return mip_path
    if mip == 0:
        fallback = runtime_dir / f"{prefix}.exr"
        if fallback.exists():
            return fallback
    raise FileNotFoundError(f"Missing {prefix} mip {mip} in {runtime_dir}")


def create_boxavg_runtime(src: Path, dst: Path, mip_count: int, metadata: dict) -> Path:
    print(f"[boxavg] creating {dst}")
    if dst.exists():
        shutil.rmtree(dst)
    copy_non_latent_files(src, dst)

    mip_shapes: list[tuple[int, int]] = []
    for prefix in LATENT_PREFIXES:
        current = read_exr_rgba(latent_path(src, prefix, 0))
        for mip in range(mip_count):
            if mip > 0:
                current = average_2x2(current)
            write_exr_rgba_half(dst / f"{prefix}_mip{mip}.exr", current)
            if prefix == "latent0":
                mip_shapes.append((current.shape[1], current.shape[0]))
            if mip == 0:
                write_exr_rgba_half(dst / f"{prefix}.exr", current)

    write_metadata(dst, metadata, mip_shapes)
    return dst


def create_force_mip_runtime(src: Path, dst: Path, mip: int, metadata: dict) -> Path:
    print(f"[force] creating {dst}")
    if dst.exists():
        shutil.rmtree(dst)
    copy_non_latent_files(src, dst)
    remove_latents(dst)

    shapes: list[tuple[int, int]] = []
    for prefix in LATENT_PREFIXES:
        rgba = read_exr_rgba(latent_path(src, prefix, mip))
        write_exr_rgba_half(dst / f"{prefix}.exr", rgba)
        if prefix == "latent0":
            shapes.append((rgba.shape[1], rgba.shape[0]))
    write_metadata(dst, metadata, shapes)
    return dst


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare trained-vs-boxavg mip comparison runtime folders.")
    parser.add_argument("--trained-runtime", type=Path, required=True)
    parser.add_argument("--out-root", type=Path, required=True)
    parser.add_argument("--mip-count", type=int, default=None)
    parser.add_argument("--name-prefix", default="finetune_600000")
    parser.add_argument(
        "--skip-force-mip-folders",
        action="store_true",
        help="Only create the box-averaged hierarchical runtime.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    trained_runtime = args.trained_runtime.resolve()
    out_root = args.out_root.resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    mip_count = args.mip_count or detect_mip_count(trained_runtime)
    metadata = load_metadata(trained_runtime)

    trained_copy_runtime = out_root / f"{args.name_prefix}_trained_runtime"
    copy_runtime_tree(trained_runtime, trained_copy_runtime)

    boxavg_runtime = out_root / f"{args.name_prefix}_boxavg_runtime"
    create_boxavg_runtime(trained_runtime, boxavg_runtime, mip_count, metadata)

    manifest = {
        "trained_runtime": str(trained_runtime),
        "trained_copy_runtime": str(trained_copy_runtime),
        "boxavg_runtime": str(boxavg_runtime),
        "mip_count": mip_count,
        "force_mip_runtimes": [],
    }

    if not args.skip_force_mip_folders:
        for variant, source in (("trained", trained_runtime), ("boxavg", boxavg_runtime)):
            for mip in range(mip_count):
                dst = out_root / f"{args.name_prefix}_{variant}_force_mip{mip}_runtime"
                create_force_mip_runtime(source, dst, mip, metadata)
                manifest["force_mip_runtimes"].append(
                    {"variant": variant, "mip": mip, "runtime": str(dst)}
                )

    (out_root / "mip_comparison_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"[done] wrote mip comparison assets to {out_root}")


if __name__ == "__main__":
    main()
